# Generated by Django 3.0.8 on 2020-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeout', '0002_auto_20200805_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceout',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
