# Generated by Django 3.0.8 on 2020-08-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeout', '0003_invoiceout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceout',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
