# Generated by Django 3.0.8 on 2020-07-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storein', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine', to='storein.Dealer'),
        ),
        migrations.CreateModel(
            name='MedicineHasDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField(null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storein.Medicine')),
            ],
        ),
    ]
