# Generated by Django 3.0.8 on 2020-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storein', '0002_auto_20200727_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='batch_number',
        ),
        migrations.AlterField(
            model_name='medicinehasdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
