# Generated by Django 3.0.8 on 2020-07-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storein', '0003_auto_20200727_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_by', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('total_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceInDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storein.InvoiceIn')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(null=True)),
                ('quantity', models.IntegerField()),
                ('cost_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='unit_price',
            new_name='selling_rate',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='common_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='MedicineHasDetails',
        ),
        migrations.AddField(
            model_name='medicinedetails',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storein.Medicine'),
        ),
        migrations.AddField(
            model_name='invoiceindetails',
            name='medicine_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storein.MedicineDetails'),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storein.Dealer'),
        ),
    ]
