# Generated by Django 3.0.8 on 2020-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storein', '0004_auto_20200727_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='capsules_per_foil',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='foils_per_packet',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='invoicein',
            name='bought_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
