# Generated by Django 3.0.8 on 2020-07-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storein', '0005_auto_20200731_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='remaining_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoicein',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
