# Generated by Django 3.0.8 on 2020-08-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storein', '0006_auto_20200731_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='present_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
